In [3]:
class demo:
    def test(self):
        print("test() for the class and method")
        return
obj=demo()
obj.test()

test() for the class and method


In [4]:
def test():
    print('test() for function')
    return
test()

test() for function


In [11]:
class demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
    
p1=demo1()
print(p1.fact(5))

120


In [12]:
class demo2:
    def accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display(self):
        print("a= ",a)
        print("b= ",b)
        
c1=demo2()
c1.accept(10,20)
c1.display( )

NameError: name 'a' is not defined

In [15]:
class demo2:
    def _int_(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
c1=demo2()
print(c1.add(100,200))

300


In [1]:
sentence='we are humans'
matched=re.match(r'(.*)(.*?)(.*)',sentence)
print(matched.group(2))

NameError: name 're' is not defined

In [7]:
class person(object):
    def _init_(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
    
class employee(person):
    def isemployee(self):
        return True
    
emp=person("anil")
print(emp.getname(),emp.isemployee())
emp1=employee("akhil")
print(emp.getname(),emp.isemployee())

TypeError: person() takes no arguments

In [8]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [9]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [10]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int64


In [11]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [3]:

import numpy as np
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
import numpy as np
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [6]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np
a1=np.random.normal(5,0.5,10)
print(a1)

[5.10121657 4.96797858 5.06830455 5.02776699 5.12261521 5.07907309
 4.93858135 5.17088486 4.49631786 4.76259614]


In [9]:
import numpy as np
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
import numpy as np
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]])

In [11]:
import numpy as np
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [12]:
import numpy as np
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [13]:
import numpy as np
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [14]:
import numpy as np
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)


[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]
