In [2]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [5]:
import numpy as np
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [14]:
import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print("First Row: ",a1[0])

First Row:  [1 2 3]


In [19]:
import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,1])

slicing column: [2 5]


In [25]:
import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print("Second Row: ",a1[1])

Second Row:  [4 5 6]


In [21]:
import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [22]:
import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last column: ",a1[:,2])

slicing last column:  [3 6]


In [23]:
import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print("row and column : ",a1[1,:1])

row and column :  [4]


In [31]:
import numpy as np
a1=np.random.normal(5,1,10)
print(a1)
print("min value: ",np.min(a1))
print("max value: ",np.max(a1))
print("median value: ",np.median(a1))
print("mean value: ",np.mean(a1))

[6.87654636 5.33130837 4.57195979 4.16628253 5.91056061 4.96281787
 4.59034214 4.61110555 3.86487323 6.0303158 ]
min value:  3.864873226925334
max value:  6.87654635813586
median value:  4.786961712546455
mean value:  5.091611225718359


In [32]:
import numpy as np
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [35]:
import numpy as np
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [36]:
import numpy as np
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [40]:
import pandas as pd
dict={"name":["arjun","varun","goutham","dolly","sush","srav"],"emailid":["arjun@gmail.com","varun@gmail.com","goutham@gmail.com","dolly@gmail.com","sush@gmail.com","srav@gmail.com"],"mobilenumber":[999,888,777,666,555,444],"address":["hyd","hyd","hyd","hyd","hyd","hyd"]}
b=pd.DataFrame(dict)
print(b)

      name            emailid  mobilenumber address
0    arjun    arjun@gmail.com           999     hyd
1    varun    varun@gmail.com           888     hyd
2  goutham  goutham@gmail.com           777     hyd
3    dolly    dolly@gmail.com           666     hyd
4     sush     sush@gmail.com           555     hyd
5     srav     srav@gmail.com           444     hyd


In [41]:
b.index=["01","02","03","04","05","06"]
print(b)

       name            emailid  mobilenumber address
01    arjun    arjun@gmail.com           999     hyd
02    varun    varun@gmail.com           888     hyd
03  goutham  goutham@gmail.com           777     hyd
04    dolly    dolly@gmail.com           666     hyd
05     sush     sush@gmail.com           555     hyd
06     srav     srav@gmail.com           444     hyd


In [ ]:
import pandas as pd
product_sellingdata=pd.read_csv("filename.csv",index_col=1)
print(product_sellingdata)